config/routes.rb
Rails.application.routes.draw do
  get '/profile/edit' => 'profiles#edit'
  post '/profile/update' => 'profiles#update'
  
  get '/todos/notice/:id/checked' => 'notices#checked'

    # get '/todos/:todo_id/comment/:id/report' => 'comments#report'
    # get '/todos/:todo_id/comment'  => 'comments#show'
    # get '/todos/:todo_id/comment/new' => 'comments#new'
    # post '/todos/:todo_id/comment/create'  => 'comments#create'
    # get '/todos/:todo_id/comment/:id'  => 'comments#destroy'
    # get '/todos/comment/:id/edit' => 'comments#edit'
    # post '/todos/comment/:id/update' => 'comments#update'

  get '/login' => 'users#yourdetil'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
 
  resources :users
  resources :todos do
    resources :fights, only: [:create, :destroy]
    member do
      post 'done'
    end
    resources 'comments', except: [:show] do
      member do
        get 'report'
      end
    end
  end

  get '/' => "home#top", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @todo = ToDo.where(user_id: session[:user_id], done: false).includes(:fights, :comments).order(limit_date: "ASC")
    @todo_done = ToDo.where(user_id: session[:user_id], done: true).includes(:fights, :comments).order(limit_date: "DESC")

    
    @todo_fight = Fight.where(user_id: session[:user_id]).includes(:user, :to_do).order(created_at: "DESC")
    @user = User.find(session[:user_id])
  end

  def show
    @todo = ToDo.where(public: true).includes(:user, :fights).order(id: "DESC")
    @todo_fight = ToDo.where(public: true).includes(:user, :fights).order(fight: "DESC")
  end

  def yourshow
    @todo = ToDo.where(user_id: params[:user_id])
  end

  def new
    @todo = ToDo.new
  end

  def create
    @todo = ToDo.new(
      text: params[:text],
      user_id: session[:user_id],
      limit_date: params[:date],
      done: false,
      fight: 0,
      comment: 0
    )
    @user = User.find(session[:user_id])
    if @user.public
      @todo.public = true
    else
      @todo.public = false
    end
    if @todo[:limit_date].nil?
      flash[:attention] = "リミット日時を正しく入力してください"
      render:new, status: :unprocessable_entity
    elsif @todo[:text].blank?
      flash[:attention] = "テキストを正しく入力してください"
      render:new, status: :unprocessable_entity
    elsif @todo.save
      flash[:notice] = "タスクの登録に成功しました"
      redirect_to("/tasks")
    else
      flash[:attention] = "何か入力ミスをしています
      。確認してください。"
      render:new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = ToDo.find(params[:id])
  end

  def update
    @todo = ToDo.find(params[:id])
    @todo.text = params[:text]
    @todo.limit_date = params[:date]
    if params[:public] == "true"
      @todo.public = true
    elsif params[:public] == "false"
      @todo.public = false
    end
    if @todo[:limit_date].nil?
      flash[:attention] = "リミット日時を正しく入力してください"
      render:edit, status: :unprocessable_entity
    elsif @todo[:text].blank?
      flash[:attention] = "テキストを正しく入力してください"
      render:edit, status: :unprocessable_entity
    elsif @todo.save
      flash[:notice] = "編集が完了しました"
      redirect_to("/tasks")
    else
      flash[:attention] = ["何か問題が発生しています", "確認してください"]
      render:edit, status: :unprocessable_entity
    end
  end

  def delete
    @todo = ToDo.find(params[:id])
    @todo.destroy
    flash[:notice] = "タスクを削除しました"
    redirect_to("/tasks")
  end

  def done
    @todo = ToDo.find(params[:id])
    if @todo.done
      @todo.update(done: false)
      redirect_to tasks_path
    else
      @todo.update(done: true)
      redirect_to tasks_path
    end
  end

  def yourshow
    @user = User.find(params[:id])
    @todos = Todo,where(user_id: params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper


end

app/views/tasks/edit.html.erb
<div class="todo">
  <div class="todo-header">
    <h1>ToDo編集</h1>
    <div class="todo_main">
      <% @todo.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>

      <%= form_tag("/tasks/update") do %>
        <p>テキスト</p>
        <input name="text" value="<%= @todo.text %>">
        <p>リミット日時 例）2023-8-3</p>
        <input name="date" value="<%= @todo.limit_date %>">
        </br>
        <input type="hidden" name="id" value="<%= @todo.id %>">
        <div class="submit-button">
          <input type="submit" value="編集する">
        </div>
      <% end %>
      <%= form_tag ("/tasks/delete") do %>
        <input type="hidden" name="id" value="<%= @todo.id %>">
        <input type="submit" value="削除する" class="show-btn">
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="todo-header">
  <h1>Myリスト</h1>
  <div class="user-show-body">
    <div class="user-show-switch">
      <p class="cvevron-down active">ユーザー詳細</p>
      <div class="cvevron-down active"><i class="fas fa-chevron-down"></i></div>
    </div>
    <div class="user-show-box">
      <div class="active-grid">
        <div class="user-show-border">
          <%= image_tag "#{@user.user_image.cropped}", class:"user-show-img"%>
        </div>
        <div class="user-show-text">
          <h2 class="user-show-name"><%= @user.name %></h2>
          <p><%= @user.email %></p>
          <p><a class="user-show-label">達成済タスク：</a><%= @todo_done.count %></p>
          <p><a class="user-show-label">未達成タスク：</a><%= @todo.count %></p>
          <% if @user.public %>
            <p>公開</p>
          <% else %>
            <p>非公開</p>
          <% end %>
        </div>
      </div>
      <%= link_to("ユーザー情報編集", "/users/#{@user.id}/edit", class:"userEditList") %>
      <div class="chevron-up user-show-switch">
        <i class="fas fa-chevron-up"></i>
      </div>
    </div>    
  </div>
</div>
<div class="todo">
  <div class="tab-list">
    <ul class="tab-con">
      <li class="tab tab-active">未達成</li>
      <li class="tab">達成済</li>
      <li class="tab">応援</li>
    </ul>
  </div>
  <div class="todo-body">
    <div class="todo-list-box todo-index-active">
    <h2>未達成タスク</h2>
    <%= link_to("ToDoを追加しよう", "/tasks/new", class: "list-text") %>
    <div class="todo-box">
        <% @todo.each do |todo| %>
          <div class="todo-list <%= 'todo-list-out' if todo.limit_date <= Date.today %>">
          <div class="list-grid">
            <%= link_to "/tasks/#{todo.id}/comment",class: "comment-link" do %> 
              <p class="todo-list-text index-text-box"><%= todo.text %></p>
            <% end %>
            <%= link_to "/tasks/#{todo.id}/comment",class: "comment-link" do %> 
              <div class="limit-box"><p class="index-limit"><%= todo.limit_date %></p></div> 
            <% end %>
            <div class="index-btn-box">
                <%= button_to '完了', done_path(todo.id),  date:{"turbo-method": :post}, class:"index-done-btn"%>
              </div>
          </div>

          <div class="sub-cont">
          <% todo.fights.each do |fight, n| %>
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if n == todo.fights.size - 1 %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% if todo.fights.size == 0 %>
            <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/tasks/#{todo.id}/comment/new", class: "fas_header_bordertransparent") %>  
          <%= link_to("","/tasks/#{todo.id}/edit", class: "fas fa-pen fa-lg edit-pen") %>
          </div>
        </div>
      <% end %>
    </div>   
    </div>
        
      

    <div class="todo-list-box">
        <% if @todo_done.size == 0%>
          <h2>達成済タスク</h2>
          <%= link_to("ToDoを追加しよう", "/tasks/new", class: "list-text") %>
        <% else %>
          <h2>達成済タスク</h2>
          <% @todo_done.each do |todo| %>
            <div class="todo-list">
              <div class="list-grid">
                <%= link_to "/tasks/#{todo.id}/comment",class:  "comment-link" do %> 
                  <p class="todo-list-text index-text-box"><%= todo.text %></p>
                <% end %>
                <%= link_to "/tasks/#{todo.id}/comment",class: "comment-link" do %> 
                  <div class="limit-box"><p class="index-limit"><%= todo.limit_date %></p></div> 
                <% end %>
                <div class="index-btn-box">
                  <%= button_to '未完了', done_path(todo.id),  date:{"turbo-method": :post}, class:"index-done-btn"%>
                </div>
              </div>
              <div class="sub-cont">
              <% todo.fights.each do |fight, n| %>
                <% if fight.user_id == session[:user_id] %>
                  <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
                  <% break %> 
                <% end %>
                <% if n == todo.fights.size - 1 %>
                  <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
                <% end %>
              <% end %>
              <% if todo.fights.size == 0 %>
                <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
              <% end %>
              <%= link_to("#{todo.comment}", "/tasks/#{todo.id}/comment/new", class: "fas_header_bordertransparent") %>

              <%= link_to("","/tasks/#{todo.id}/edit", class: "fas fa-pen fa-lg edit-pen") %>
              </div>
            </div>
          <% end %>    
        <% end %>
      </div>

      <div class="todo-list-box">
        <% if @todo_fight.size == 0%>
          <% m = 1 %>
          <h2>応援タスク</h2>
          <%= link_to("他の人のタスクを応援する", "/tasks/list",class: "fight-path") %>
        <% else %>
        <h2>応援タスク</h2>
          <% @todo_fight.each do |fight| %>
            <div class="fight-todo-box">
            <%= link_to "/tasks/#{fight.to_do.id}/comment",class: "comment-link" do %> 
              <h2><%= fight.to_do.user.name %></h2>
              <p class="todo-text"><%= fight.to_do.text %></p>
              <p class="todo-date"><%= fight.to_do.limit_date %></p>
              <% @todo_fight.each do |f, n| %>
                <% if f.user_id == session[:user_id] %>
                  <%= link_to("#{fight.to_do.fight}","/tasks/#{fight.to_do.id}/fight/#{f.id}", class: "fas_button_border_after") %>
                  <% break %> 
                <% end %>
                <% if n == todo.fights.size - 1 %>
                  <%= link_to("#{todo.to_do.fight}","/tasks/#{todo.to_do.id}/fight", class: "fas_button_border") %>
                <% end %>
              <% end %>
              <% if fight.to_do.fight == 0 %>
                <%= link_to("#{fight.to_do.f}","/tasks/#{fight.to_do.id}/fight", class: "fas_button_border") %>
              <% end %>
              <%= link_to("#{fight.to_do.comment}", "/tasks/#{fight.to_do.id}/comment/new", class: "fas_header_bordertransparent") %>
            <% end %>
            </div>
          <% end %>    
        <% end %>
      </div>
    </div>
        
  
</div>

app/views/tasks/new.html.erb
<div class="todo">
  <div class="todo-header">
    <h1>ToDo追加</h1>
    <div class="todo_main">
      <% @todo.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>

      <%= form_tag("/tasks/create") do %>
        <p>テキスト</p>
        <input name="text" value="<%= @todo.text %>">
        <p>リミット日時 例）2023-8-3</p>
        <input name="date" value="<%= @todo.limit_date %>">
        </br>
        <div class="submit-button">
          <input type="submit" value="追加する">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="todo">
  <div class="todo-header">

    <div class="tab-list">
    <ul class="tab-con">
      <li class="tab tab-active">新着順</li>
      <li class="tab">人気順</li>
    </ul>
    </div>
  </div>
  <div class="todo-body">
    <div class="todo-list-box todo-index-active">
    <% @todo.each do |todo| %>
      <div class="show-todo-box">
        <%= link_to "/tasks/#{todo.id}/comment",class: "comment-link" do %>
          <div class="text-left">
            <%= image_tag "#{todo.user.user_image.cropped}", class:"todo-user-img"%>
            <h2><%= todo.user.name %></h2>
          </div>
          <p class="todo-text"><%= todo.text %></p>
          <p class="todo-date"><%= todo.limit_date %></p>
          <% if todo.fight > 0 %>

          <% todo.fights.each_with_index do |fight, i| %>
            
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if i == todo.fight - 1 %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% elsif todo.fight == 0 %>
            <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/tasks/#{todo.id}/comment/new", class: "fas_header_bordertransparent") %>
        <% end %>
      </div>
    <% end %>
    </div>

    <div class="todo-list-box">
      <% @todo_fight.each do |todo| %>
        <div class="show-todo-box">
        <%= link_to "/tasks/#{todo.id}/comment",class: "comment-link" do %> 
          <div class="text-left">
            <%= image_tag "#{todo.user.user_image.cropped}", class:"todo-user-img"%>
            <h2><%= todo.user.name %></h2>
          </div>
          <p class="todo-text"><%= todo.text %></p>
          <p class="todo-date"><%= todo.limit_date %></p>
          <% todo.fights.each_with_index do |fight, n| %>
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if n == todo.fights.size - 1 %>
              <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% if todo.fights.size == 0 %>
            <%= link_to("#{todo.fight}","/tasks/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/tasks/#{todo.id}/comment/new", class: "fas_header_bordertransparent") %>
        <% end %>
        </div>
      <% end %>
    </div>    
  </div>
</div>