config/routes.rb
Rails.application.routes.draw do
  get '/profile/edit' => 'profiles#edit'
  post '/profile/update' => 'profiles#update'
  
  get '/todos/notice/:id/checked' => 'notices#checked'

    # get '/todos/:todo_id/comment/:id/report' => 'comments#report'
    # get '/todos/:todo_id/comment'  => 'comments#show'
    # get '/todos/:todo_id/comment/new' => 'comments#new'
    # post '/todos/:todo_id/comment/create'  => 'comments#create'
    # get '/todos/:todo_id/comment/:id'  => 'comments#destroy'
    # get '/todos/comment/:id/edit' => 'comments#edit'
    # post '/todos/comment/:id/update' => 'comments#update'

  get '/login' => 'users#yourdetil'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
 
  resources :users
  resources :todos do
    resources :fights, only: [:create, :destroy]
    member do
      post 'done'
    end
    resources 'comments', except: [:show] do
      member do
        get 'report'
      end
    end
  end

  get '/' => "home#top", as: 'home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  has_many :fights, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :notices, dependent: :destroy
  belongs_to :user

  validates :public, inclusion: { in: [true, false] }
  
  def fighted?(user_id)
    fights.where(user_id: user_id).exists?
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :fights, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :notices, dependent: :destroy
  belongs_to :user

  validates :text, presence: { message: "を入力してください" }
  validates :limit_date, presence: { message: "を入力してください" }
  validate :limit_date_in_past
  validates :fight, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comment, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }
  
  def fighted?(user_id)
    fights.where(user_id: user_id).exists?
  end

  private 
    def limit_date_in_past
      if limit_date.present? && limit_date < Date.today
        errors.add(:limit_date, "を過去に設定はできません")
      end
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.where(user_id: session[:user_id], done: false).includes(:fights, :comments).order(limit_date: "ASC")
    @todo_done = Todo.where(user_id: session[:user_id], done: true).includes(:fights, :comments).order(limit_date: "DESC")

    
    @todo_fight = Fight.where(user_id: session[:user_id]).includes(:user, :todo).order(created_at: "DESC")
    @user = User.find(session[:user_id])
  end

  def show
    @todo = Todo.where(public: true).includes(:user, :fights).order(id: "DESC")
    @todo_fight = Todo.where(public: true).includes(:user, :fights).order(fight: "DESC")
  end
  
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @user = User.find(session[:user_id])
    if @user.public
      @todo.public = true
    else
      @todo.public = false
    end
    if @todo.save
      flash[:notice] = "タスクの登録に成功しました"
      redirect_to("/todos")
    else
      render :new, flash: { error: @todo.errors.full_messages }
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      flash[:notice] = "編集が完了しました"
      redirect_to @todo
    else
      render :edit 
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path, notice: "タスクを削除しました"
  end

  def done
    @todo = Todo.find(params[:id])
    if @todo.done
      @todo.update(done: false)
      redirect_to todos_path
    else
      @todo.update(done: true)
      redirect_to todos_path
    end
  end

  private
    def todo_params
      params.require(:todo).permit(:text, :limit_date, :public, :user_id, :done, :fight, :comment)
    end
end

app/views/todos/edit.html.erb
<div class="todo">
  <div class="todo-header">
    <h1>ToDo編集</h1>
    <div class="todo_main">
      <% @todo.errors.full_messages.each do |message| %>
        <div class="form-error">
          <%= message %>
        </div>
      <% end %>

      <%= form_with(model: @todo, local: true) do |form| %>
        <div class="field">
          <p><%= form.label :text %></p>  
          <%= form.text_field :text, value: @todo.text %>
        </div>
        <div class="field">
          <p><%= form.label :limit_date %></p>
          <%= form.date_field :limit_date, value: @todo.limit_date %>
        </div>
        
        </br>
        <div class="submit-button">
          <%= form.submit '編集する' %>
        </div>
      <% end %>
      <%= form_with(url: todo_path(@todo), local:true, method: :delete) do %>
        <input type="hidden" name="id" value="<%= @todo.id %>">
        <input type="submit" value="削除する" class="show-btn">
      <% end %>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class="todo-header">
  <h1>Myリスト</h1>
  <div class="user-show-body">
    <div class="user-show-switch">
      <p class="cvevron-down active">ユーザー詳細</p>
      <div class="cvevron-down active"><i class="fas fa-chevron-down"></i></div>
    </div>
    <div class="user-show-box">
      <div class="active-grid">
        <div class="user-show-border">
          <%= image_tag "#{@user.user_image.cropped}", class:"user-show-img"%>
        </div>
        <div class="user-show-text">
          <h2 class="user-show-name"><%= @user.name %></h2>
          <p><%= @user.email %></p>
          <p><a class="user-show-label">達成済タスク：</a><%= @todo_done.count %></p>
          <p><a class="user-show-label">未達成タスク：</a><%= @todo.count %></p>
          <% if @user.public %>
            <p>公開</p>
          <% else %>
            <p>非公開</p>
          <% end %>
        </div>
      </div>
      <%= link_to("ユーザー情報編集", "/users/#{@user.id}/edit", class:"userEditList") %>
      <div class="chevron-up user-show-switch">
        <i class="fas fa-chevron-up"></i>
      </div>
    </div>    
  </div>
</div>
<div class="todo">
  <div class="tab-list">
    <ul class="tab-con">
      <li class="tab tab-active">未達成</li>
      <li class="tab">達成済</li>
      <li class="tab">応援</li>
    </ul>
  </div>
  <div class="todo-body">
    <div class="todo-list-box todo-index-active">
    <h2>未達成タスク</h2>
    <%= link_to("ToDoを追加しよう", "/todos/new", class: "list-text") %>
    <div class="todo-box">
        <% @todo.each do |todo| %>
          <div class="todo-list <%= 'todo-list-out' if todo.limit_date <= Date.today %>">
          <div class="list-grid">
            <%= link_to "/todos/#{todo.id}/comments",class: "comment-link" do %> 
              <p class="todo-list-text index-text-box"><%= todo.text %></p>
            <% end %>
            <%= link_to "/todos/#{todo.id}/comments",class: "comment-link" do %> 
              <div class="limit-box"><p class="index-limit"><%= todo.limit_date %></p></div> 
            <% end %>
            <div class="index-btn-box">
                <%= button_to '完了', done_todo_path(todo.id),  date:{"turbo-method": :post}, class:"index-done-btn"%>
              </div>
          </div>

          <div class="sub-cont">
          <% todo.fights.each do |fight, n| %>
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if n == todo.fights.size - 1 %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% if todo.fights.size == 0 %>
            <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/todos/#{todo.id}/comments/new", class: "fas_header_bordertransparent") %>  
          <%= link_to("","/todos/#{todo.id}/edit", class: "fas fa-pen fa-lg edit-pen") %>
          </div>
        </div>
      <% end %>
    </div>   
    </div>
        
      

    <div class="todo-list-box">
        <% if @todo_done.size == 0%>
          <h2>達成済タスク</h2>
          <%= link_to("ToDoを追加しよう", "/todos/new", class: "list-text") %>
        <% else %>
          <h2>達成済タスク</h2>
          <% @todo_done.each do |todo| %>
            <div class="todo-list">
              <div class="list-grid">
                <%= link_to "/todos/#{todo.id}/comments",class:  "comment-link" do %> 
                  <p class="todo-list-text index-text-box"><%= todo.text %></p>
                <% end %>
                <%= link_to "/todos/#{todo.id}/comments",class: "comment-link" do %> 
                  <div class="limit-box"><p class="index-limit"><%= todo.limit_date %></p></div> 
                <% end %>
                <div class="index-btn-box">
                  <%= button_to '未完了', done_todo_path(todo.id),  date:{"turbo-method": :post}, class:"index-done-btn"%>
                </div>
              </div>
              <div class="sub-cont">
              <% todo.fights.each do |fight, n| %>
                <% if fight.user_id == session[:user_id] %>
                  <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
                  <% break %> 
                <% end %>
                <% if n == todo.fights.size - 1 %>
                  <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
                <% end %>
              <% end %>
              <% if todo.fights.size == 0 %>
                <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
              <% end %>
              <%= link_to("#{todo.comment}", "/todos/#{todo.id}/comments/new", class: "fas_header_bordertransparent") %>

              <%= link_to("","/todos/#{todo.id}/edit", class: "fas fa-pen fa-lg edit-pen") %>
              </div>
            </div>
          <% end %>    
        <% end %>
      </div>

      <div class="todo-list-box">
        <% if @todo_fight.size == 0%>
          <% m = 1 %>
          <h2>応援タスク</h2>
          <%= link_to("他の人のタスクを応援する", "/todos/list",class: "fight-path") %>
        <% else %>
        <h2>応援タスク</h2>
          <% @todo_fight.each do |fight| %>
            <div class="fight-todo-box">
            <%= link_to "/todos/#{fight.todo.id}/comment",class: "comment-link" do %> 
              <h2><%= fight.todo.user.name %></h2>
              <p class="todo-text"><%= fight.todo.text %></p>
              <p class="todo-date"><%= fight.todo.limit_date %></p>
              <% @todo_fight.each do |f, n| %>
                <% if f.user_id == session[:user_id] %>
                  <%= link_to("#{fight.todo.fight}","/todos/#{fight.todo.id}/fight/#{f.id}", class: "fas_button_border_after") %>
                  <% break %> 
                <% end %>
                <% if n == todo.fights.size - 1 %>
                  <%= link_to("#{todo.todo.fight}","/todos/#{todo.todo.id}/fight", class: "fas_button_border") %>
                <% end %>
              <% end %>
              <% if fight.todo.fight == 0 %>
                <%= link_to("#{fight.todo.f}","/todos/#{fight.todo.id}/fight", class: "fas_button_border") %>
              <% end %>
              <%= link_to("#{fight.todo.comment}", "/todos/#{fight.todo.id}/comment/new", class: "fas_header_bordertransparent") %>
            <% end %>
            </div>
          <% end %>    
        <% end %>
      </div>
    </div>
        
  
</div>

app/views/todos/new.html.erb
<div class="todo">
  <div class="todo-header">
    <h1>ToDo追加</h1>
    <div class="todo_main">
      <% if @todo.errors.present? %>
        <% @todo.errors.full_messages.each do |message| %>
          <div class="form-error">
            <%= message %>
          </div>
        <% end %>
      <% end %>

      <%= form_with(model: @todo, local: true) do |form| %>
        <div class="field">
          <p><%= form.label :text %></p>
          <%= form.text_field :text %>
        </div>
        <div class="field">
          <p><%= form.label :limit_date %></p>
          <%= form.date_field :limit_date %>
        </div>
        <%= form.hidden_field :user_id, value: session[:user_id] %>
        <div class="submit-button">
          <%= form.submit '追加する' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<div class="todo">
  <div class="todo-header">

    <div class="tab-list">
    <ul class="tab-con">
      <li class="tab tab-active">新着順</li>
      <li class="tab">人気順</li>
    </ul>
    </div>
  </div>
  <div class="todo-body">
    <div class="todo-list-box todo-index-active">
    <% @todo.each do |todo| %>
      <div class="show-todo-box">
        <%= link_to "/todos/#{todo.id}/comments",class: "comment-link" do %>
          <div class="text-left">
            <%= image_tag "#{todo.user.user_image.cropped}", class:"todo-user-img"%>
            <h2><%= todo.user.name %></h2>
          </div>
          <p class="todo-text"><%= todo.text %></p>
          <p class="todo-date"><%= todo.limit_date %></p>
          <% if todo.fight > 0 %>

          <% todo.fights.each_with_index do |fight, i| %>
            
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if i == todo.fight - 1 %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% elsif todo.fight == 0 %>
            <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/todos/#{todo.id}/comments/new", class: "fas_header_bordertransparent") %>
        <% end %>
      </div>
    <% end %>
    </div>

    <div class="todo-list-box">
      <% @todo_fight.each do |todo| %>
        <div class="show-todo-box">
        <%= link_to "/todos/#{todo.id}/comments",class: "comment-link" do %> 
          <div class="text-left">
            <%= image_tag "#{todo.user.user_image.cropped}", class:"todo-user-img"%>
            <h2><%= todo.user.name %></h2>
          </div>
          <p class="todo-text"><%= todo.text %></p>
          <p class="todo-date"><%= todo.limit_date %></p>
          <% todo.fights.each_with_index do |fight, n| %>
            <% if fight.user_id == session[:user_id] %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight/#{fight.id}", class: "fas_button_border_after") %>
              <% break %> 
            <% end %>
            <% if n == todo.fights.size - 1 %>
              <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
            <% end %>
          <% end %>
          <% if todo.fights.size == 0 %>
            <%= link_to("#{todo.fight}","/todos/#{todo.id}/fight", class: "fas_button_border") %>
          <% end %>
          <%= link_to("#{todo.comment}", "/todos/#{todo.id}/comments/new", class: "fas_header_bordertransparent") %>
        <% end %>
        </div>
      <% end %>
    </div>    
  </div>
</div>

app/views/todos/yourshow.html.erb
<div class="todo">
  <div class="todo-header">
    <h1><%= @user.name %>さん</h1>
    <div class="tab-list">
      <ul class="tab-con">
        <li class="show-tab show-tab-active">未完了</li>
        <li class="show-tab">完了</li>
      </ul>
    </div>
  </div>
  <div class="todo-body">
    <div class="todo-list-box show-active">
      <% if @todos.blank? %>
        <p>この人はToDoがまだありません</p>
      <% else %>
        <h2>未完了タスク</h2>
        <% @todos.each do |todo| %>
        <% end %>
    </div>
  </div>
</div>